### ISSUE TITLE
Sent u a discord friend request also im curious how people make these stuff

### ISSUE THREAD

**Issue by able-j** [Uploader2503/KRCheat#1]
My discord is yee#5017

**Comment by XD493** [comment]
why u doing new issue, when u just must wait to accept ur friend request on discord
i answer you, by bypassing the anticheat and writing boring rotating function in aimbot

**Comment by able-j** [comment]
Yes, and I cant implement it.

**Comment by able-j** [comment]
Also krunker updated to 1.6.0, can u update too

**Comment by darkdragon1076** [comment]
It's been 3 years since last post , but can you let me know of ur new aimbots. I already friended you.
TY.

**Comment by able-j** [comment]
dude that discord acc is deleted. that's so long ago I don't even touch this anymore lol
